// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: company.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO recycle.company (id, name, company_owner_id, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, company_owner_id, created_at, updated_at, deleted_at, created_by, updated_by
`

type CreateCompanyParams struct {
	ID             pgtype.UUID
	Name           string
	CompanyOwnerID pgtype.UUID
	CreatedBy      pgtype.UUID
	UpdatedBy      pgtype.UUID
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (RecycleCompany, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.Name,
		arg.CompanyOwnerID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i RecycleCompany
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CompanyOwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const findCompanyById = `-- name: FindCompanyById :one
SELECT
    company.id, company.name, company.company_owner_id, company.created_at, company.updated_at, company.deleted_at, company.created_by, company.updated_by,
    users.id, users.email, users.hashed_password, users.confirmed_at, users.confirmation_token, users.role, users.created_at, users.updated_at, users.deleted_at, users.created_by, users.updated_by
FROM recycle.company company
INNER JOIN recycle.user users ON company.company_owner_id = users.id
WHERE company.id = $1
`

type FindCompanyByIdRow struct {
	RecycleCompany RecycleCompany
	RecycleUser    RecycleUser
}

func (q *Queries) FindCompanyById(ctx context.Context, id pgtype.UUID) (FindCompanyByIdRow, error) {
	row := q.db.QueryRow(ctx, findCompanyById, id)
	var i FindCompanyByIdRow
	err := row.Scan(
		&i.RecycleCompany.ID,
		&i.RecycleCompany.Name,
		&i.RecycleCompany.CompanyOwnerID,
		&i.RecycleCompany.CreatedAt,
		&i.RecycleCompany.UpdatedAt,
		&i.RecycleCompany.DeletedAt,
		&i.RecycleCompany.CreatedBy,
		&i.RecycleCompany.UpdatedBy,
		&i.RecycleUser.ID,
		&i.RecycleUser.Email,
		&i.RecycleUser.HashedPassword,
		&i.RecycleUser.ConfirmedAt,
		&i.RecycleUser.ConfirmationToken,
		&i.RecycleUser.Role,
		&i.RecycleUser.CreatedAt,
		&i.RecycleUser.UpdatedAt,
		&i.RecycleUser.DeletedAt,
		&i.RecycleUser.CreatedBy,
		&i.RecycleUser.UpdatedBy,
	)
	return i, err
}
