// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RecycleCompany struct {
	ID             uuid.UUID
	Name           string
	CompanyOwnerID uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	CreatedBy      uuid.UUID
	UpdatedBy      uuid.UUID
}

type RecycleUser struct {
	ID                uuid.UUID
	Email             string
	HashedPassword    string
	ConfirmedAt       pgtype.Timestamptz
	ConfirmationToken pgtype.Text
	Role              string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         uuid.UUID
	UpdatedBy         uuid.UUID
}
