// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RecycleCompany struct {
	ID             pgtype.UUID
	Name           string
	CompanyOwnerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	UpdatedBy      pgtype.UUID
}

type RecycleUser struct {
	ID                pgtype.UUID
	Email             string
	HashedPassword    string
	ConfirmedAt       pgtype.Timestamptz
	ConfirmationToken pgtype.Text
	Role              string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
}
