// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmUserAccess = `-- name: ConfirmUserAccess :exec
UPDATE recycle.user SET confirmed_at = $2, updated_at = now(), updated_by = $3 WHERE id = $1
`

type ConfirmUserAccessParams struct {
	ID          uuid.UUID
	ConfirmedAt pgtype.Timestamptz
	UpdatedBy   uuid.UUID
}

func (q *Queries) ConfirmUserAccess(ctx context.Context, arg ConfirmUserAccessParams) error {
	_, err := q.db.Exec(ctx, confirmUserAccess, arg.ID, arg.ConfirmedAt, arg.UpdatedBy)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO recycle.user (id, email, hashed_password, confirmation_token, role, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, hashed_password, confirmed_at, confirmation_token, role, created_at, updated_at, deleted_at, created_by, updated_by
`

type CreateUserParams struct {
	ID                uuid.UUID
	Email             string
	HashedPassword    string
	ConfirmationToken pgtype.Text
	Role              string
	CreatedBy         uuid.UUID
	UpdatedBy         uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (RecycleUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.HashedPassword,
		arg.ConfirmationToken,
		arg.Role,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i RecycleUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.ConfirmedAt,
		&i.ConfirmationToken,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, email, hashed_password, confirmed_at, confirmation_token, role, created_at, updated_at, deleted_at, created_by, updated_by
FROM recycle.user WHERE id = $1
`

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (RecycleUser, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i RecycleUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.ConfirmedAt,
		&i.ConfirmationToken,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
